import { run, VERSION } from './main.ts';
import type { CliContext } from './main.ts';

function capturingCtx(cwd: string): {
  ctx: CliContext;
  stdout: string[];
  stderr: string[];
} {
  const stdout: string[] = [];
  const stderr: string[] = [];
  return {
    ctx: {
      cwd,
      env: {},
      stdout: (s: string) => stdout.push(s),
      stderr: (s: string) => stderr.push(s),
    },
    stdout,
    stderr,
  };
}

Deno.test('init scaffolds a config and config --print --json resolves it', async (t) => {
  const tmp = await Deno.makeTempDir();
  try {
    await t.step('init writes the config file', async () => {
      const cap = capturingCtx(tmp);
      const code = await run(['init', '.'], cap.ctx);
      if (code !== 0) throw new Error(`init exited ${code}: ${cap.stderr.join('\n')}`);
      const expected = 'wrote berrybench.config.ts (design: on, api: on, db: off)';
      if (cap.stdout.includes(expected) !== true) {
        throw new Error(`init stdout missing '${expected}': ${cap.stdout.join('\n')}`);
      }
      const content = await Deno.readTextFile(`${tmp}/berrybench.config.ts`);
      if (content.includes('Generated by BerryBench') !== true) {
        throw new Error('config missing generated header');
      }
      if (content.includes('design: {') !== true) {
        throw new Error('config missing design entry');
      }
    });

    await t.step('config --print --json shows design enabled', async () => {
      const cap = capturingCtx(tmp);
      const code = await run(['config', '--print', '--json'], cap.ctx);
      if (code !== 0) throw new Error(`config exited ${code}: ${cap.stderr.join('\n')}`);
      const parsed = JSON.parse(cap.stdout.join('\n'));
      if (parsed.workspaces?.design?.enabled !== true) {
        throw new Error(`design not enabled: ${JSON.stringify(parsed.workspaces)}`);
      }
    });
  } finally {
    await Deno.remove(tmp, { recursive: true });
  }
});

Deno.test('init with an absolute dir writes there, not to cwd', async (t) => {
  const target = await Deno.makeTempDir();
  const cwd = await Deno.makeTempDir();
  try {
    await t.step('config lands at the dir argument', async () => {
      const cap = capturingCtx(cwd);
      const code = await run(['init', target], cap.ctx);
      if (code !== 0) throw new Error(`init exited ${code}: ${cap.stderr.join('\n')}`);
      await Deno.readTextFile(`${target}/berrybench.config.ts`);
    });
    await t.step('cwd stays untouched', async () => {
      try {
        await Deno.stat(`${cwd}/berrybench.config.ts`);
        throw new Error('config file unexpectedly written to cwd');
      } catch (error) {
        if ((error as Error).message.includes('unexpectedly written')) throw error;
      }
    });
  } finally {
    await Deno.remove(target, { recursive: true });
    await Deno.remove(cwd, { recursive: true });
  }
});

Deno.test('init refuses to overwrite an existing config', async (t) => {
  const tmp = await Deno.makeTempDir();
  try {
    await t.step('first init succeeds', async () => {
      const cap = capturingCtx(tmp);
      const code = await run(['init', '.'], cap.ctx);
      if (code !== 0) throw new Error(`init exited ${code}: ${cap.stderr.join('\n')}`);
    });
    await t.step('second init exits 1 and reports the existing file', async () => {
      const cap = capturingCtx(tmp);
      const code = await run(['init', '.'], cap.ctx);
      if (code !== 1) throw new Error(`expected exit 1, got ${code}`);
      if (cap.stderr.join('\n').includes('berrybench.config.ts already exists') !== true) {
        throw new Error(`stderr missing overwrite message: ${cap.stderr.join('\n')}`);
      }
    });
  } finally {
    await Deno.remove(tmp, { recursive: true });
  }
});

Deno.test('--version prints the CLI version', async () => {
  const cap = capturingCtx('.');
  const code = await run(['--version'], cap.ctx);
  if (code !== 0) throw new Error(`--version exited ${code}`);
  if (cap.stdout.join('\n').trim() !== VERSION) {
    throw new Error(`version mismatch: ${cap.stdout.join('\n')}`);
  }
});

Deno.test('unknown command exits 1 with a message', async () => {
  const cap = capturingCtx('.');
  const code = await run(['bogus'], cap.ctx);
  if (code !== 1) throw new Error(`expected exit 1, got ${code}`);
  if (cap.stderr.join('\n').includes('unknown command: bogus') !== true) {
    throw new Error(`stderr missing unknown-command message: ${cap.stderr.join('\n')}`);
  }
});