import { parseProjectEnvFile, projectDirFromArgs, run, VERSION } from "./main.ts";
import type { CliContext } from "./main.ts";
import { join } from "@std/path";
import { readFileConfig } from "../core/config.ts";
import { listSnapshots, readSnapshot } from "../snapshot/mod.ts";

function capturingCtx(cwd: string): {
  ctx: CliContext;
  stdout: string[];
  stderr: string[];
} {
  const stdout: string[] = [];
  const stderr: string[] = [];
  return {
    ctx: {
      cwd,
      env: {},
      stdout: (s: string) => stdout.push(s),
      stderr: (s: string) => stderr.push(s),
    },
    stdout,
    stderr,
  };
}

Deno.test("init scaffolds a config and config --print --json resolves it", async (t) => {
  const tmp = await Deno.makeTempDir();
  let initStdout: string[] = [];
  try {
    await t.step("init writes the config file", async () => {
      const cap = capturingCtx(tmp);
      const code = await run(["init", "."], cap.ctx);
      initStdout = cap.stdout;
      if (code !== 0) throw new Error(`init exited ${code}: ${cap.stderr.join("\n")}`);
      const expected = "wrote berrybench.config.ts (design: on, api: on, db: off)";
      if (cap.stdout.includes(expected) !== true) {
        throw new Error(`init stdout missing '${expected}': ${cap.stdout.join("\n")}`);
      }
      const content = await Deno.readTextFile(`${tmp}/berrybench.config.ts`);
      if (content.includes("Generated by BerryBench") !== true) {
        throw new Error("config missing generated header");
      }
      if (content.includes("design: {") !== true) {
        throw new Error("config missing design entry");
      }
    });

    await t.step("init scaffolds the story convention on an empty project", async () => {
      await Deno.stat(`${tmp}/src/stories/button.svelte`);
      await Deno.stat(`${tmp}/src/stories/button.story.svelte`);
      if (
        initStdout.join("\n").includes(
          "scaffolded src/stories/button.story.svelte (story convention)",
        ) !==
          true
      ) {
        throw new Error(`scaffold line not printed: ${initStdout.join("\n")}`);
      }
    });

    await t.step("config --print --json shows design enabled", async () => {
      const cap = capturingCtx(tmp);
      const code = await run(["config", "--print", "--json"], cap.ctx);
      if (code !== 0) throw new Error(`config exited ${code}: ${cap.stderr.join("\n")}`);
      const parsed = JSON.parse(cap.stdout.join("\n"));
      if (parsed.workspaces?.design?.enabled !== true) {
        throw new Error(`design not enabled: ${JSON.stringify(parsed.workspaces)}`);
      }
    });
  } finally {
    await Deno.remove(tmp, { recursive: true });
  }
});

Deno.test("init with an existing src/ skips the story scaffold", async (t) => {
  const tmp = await Deno.makeTempDir();
  try {
    await Deno.mkdir(`${tmp}/src`, { recursive: true });
    await t.step("config written, scaffold skipped silently", async () => {
      const cap = capturingCtx(tmp);
      const code = await run(["init", "."], cap.ctx);
      if (code !== 0) throw new Error(`init exited ${code}: ${cap.stderr.join("\n")}`);
      await Deno.stat(`${tmp}/berrybench.config.ts`);
      if (cap.stdout.join("\n").includes("scaffolded") === true) {
        throw new Error(`scaffold line printed despite existing src/: ${cap.stdout.join("\n")}`);
      }
      try {
        await Deno.stat(`${tmp}/src/stories/button.story.svelte`);
        throw new Error("story scaffold unexpectedly created");
      } catch (error) {
        if ((error as Error).message.includes("unexpectedly created")) throw error;
      }
    });
  } finally {
    await Deno.remove(tmp, { recursive: true });
  }
});

Deno.test("init scaffolds into frontend/ when the design package lives there", async (t) => {
  const tmp = await Deno.makeTempDir();
  try {
    await Deno.mkdir(`${tmp}/frontend`, { recursive: true });
    await Deno.writeTextFile(
      `${tmp}/frontend/package.json`,
      '{"name":"web","version":"1.0.0"}\n',
    );
    await t.step("stories land under frontend/src, not root src", async () => {
      const cap = capturingCtx(tmp);
      const code = await run(["init", "."], cap.ctx);
      if (code !== 0) throw new Error(`init exited ${code}: ${cap.stderr.join("\n")}`);
      await Deno.stat(`${tmp}/frontend/src/stories/button.story.svelte`);
      if (!cap.stdout.join("\n").includes("frontend/src/stories/button.story.svelte")) {
        throw new Error(`scaffold line missing target path: ${cap.stdout.join("\n")}`);
      }
      try {
        await Deno.stat(`${tmp}/src`);
        throw new Error("root src/ unexpectedly created");
      } catch (error) {
        if ((error as Error).message.includes("unexpectedly created")) throw error;
      }
    });
  } finally {
    await Deno.remove(tmp, { recursive: true });
  }
});

Deno.test("init with an absolute dir writes there, not to cwd", async (t) => {
  const target = await Deno.makeTempDir();
  const cwd = await Deno.makeTempDir();
  try {
    await t.step("config lands at the dir argument", async () => {
      const cap = capturingCtx(cwd);
      const code = await run(["init", target], cap.ctx);
      if (code !== 0) throw new Error(`init exited ${code}: ${cap.stderr.join("\n")}`);
      await Deno.readTextFile(`${target}/berrybench.config.ts`);
    });
    await t.step("cwd stays untouched", async () => {
      try {
        await Deno.stat(`${cwd}/berrybench.config.ts`);
        throw new Error("config file unexpectedly written to cwd");
      } catch (error) {
        if ((error as Error).message.includes("unexpectedly written")) throw error;
      }
    });
  } finally {
    await Deno.remove(target, { recursive: true });
    await Deno.remove(cwd, { recursive: true });
  }
});

Deno.test("init refuses to overwrite an existing config", async (t) => {
  const tmp = await Deno.makeTempDir();
  try {
    await t.step("first init succeeds", async () => {
      const cap = capturingCtx(tmp);
      const code = await run(["init", "."], cap.ctx);
      if (code !== 0) throw new Error(`init exited ${code}: ${cap.stderr.join("\n")}`);
    });
    await t.step("second init exits 1 and reports the existing file", async () => {
      const cap = capturingCtx(tmp);
      const code = await run(["init", "."], cap.ctx);
      if (code !== 1) throw new Error(`expected exit 1, got ${code}`);
      if (cap.stderr.join("\n").includes("berrybench.config.ts already exists") !== true) {
        throw new Error(`stderr missing overwrite message: ${cap.stderr.join("\n")}`);
      }
    });
  } finally {
    await Deno.remove(tmp, { recursive: true });
  }
});

Deno.test("--version prints the CLI version", async () => {
  const cap = capturingCtx(".");
  const code = await run(["--version"], cap.ctx);
  if (code !== 0) throw new Error(`--version exited ${code}`);
  if (cap.stdout.join("\n").trim() !== VERSION) {
    throw new Error(`version mismatch: ${cap.stdout.join("\n")}`);
  }
});

Deno.test("unknown command exits 1 with a message", async () => {
  const cap = capturingCtx(".");
  const code = await run(["bogus"], cap.ctx);
  if (code !== 1) throw new Error(`expected exit 1, got ${code}`);
  if (cap.stderr.join("\n").includes("unknown command: bogus") !== true) {
    throw new Error(`stderr missing unknown-command message: ${cap.stderr.join("\n")}`);
  }
});

const FIXTURE_OPENAPI = await Deno.readTextFile(
  new URL("../ws-api/fixtures/openapi.yaml", import.meta.url),
);

/** A project with package.json (design source) + openapi.yaml (api source). */
async function scaffoldProject(root: string, openapi: string): Promise<void> {
  await Deno.writeTextFile(`${root}/package.json`, '{"name":"fixture","version":"0.0.0"}\n');
  await Deno.writeTextFile(`${root}/openapi.yaml`, openapi);
}

Deno.test("snapshot writes design+api snapshots and skips disabled db", async (t) => {
  const tmp = await Deno.makeTempDir();
  try {
    await scaffoldProject(tmp, FIXTURE_OPENAPI);
    await t.step("snapshot exits 0 with one line per workspace", async () => {
      const cap = capturingCtx(tmp);
      const code = await run(["snapshot", "."], cap.ctx);
      if (code !== 0) throw new Error(`snapshot exited ${code}: ${cap.stderr.join("\n")}`);
      const stdout = cap.stdout.join("\n");
      if (stdout.includes("db: off · skipped") !== true) {
        throw new Error(`missing db skip line: ${stdout}`);
      }
      if (/api: on \(.*\) · ok/.test(stdout) !== true) {
        throw new Error(`missing api ok line: ${stdout}`);
      }
    });
    await t.step("api snapshot parses with the fixture data", async () => {
      type ApiSnapshot = { endpointCount: number; title?: string };
      const api = await readSnapshot<ApiSnapshot>(tmp, "api");
      if (api?.endpointCount !== 3 || api.title !== "Fixture API") {
        throw new Error(`api snapshot mismatch: ${JSON.stringify(api)}`);
      }
    });
    await t.step("listSnapshots lists only enabled workspaces", async () => {
      const ids = (await listSnapshots(tmp)).sort();
      if (JSON.stringify(ids) !== JSON.stringify(["api", "design"])) {
        throw new Error(`snapshot ids: ${JSON.stringify(ids)}`);
      }
    });
    await t.step("snapshot pass also refreshed resolved-config.json", async () => {
      const raw = await Deno.readTextFile(`${tmp}/.berrybench/resolved-config.json`);
      const resolved = JSON.parse(raw) as { workspaces?: Record<string, { enabled?: boolean }> };
      if (
        resolved.workspaces?.api?.enabled !== true || resolved.workspaces?.db?.enabled !== false
      ) {
        throw new Error(`resolved-config mismatch: ${raw}`);
      }
    });
  } finally {
    await Deno.remove(tmp, { recursive: true });
  }
});

Deno.test("snapshot --strict exits 1 and reports a load error on stderr", async () => {
  const tmp = await Deno.makeTempDir();
  try {
    await scaffoldProject(tmp, ":::not yaml");
    const cap = capturingCtx(tmp);
    const code = await run(["snapshot", "--strict", "."], cap.ctx);
    if (code !== 1) throw new Error(`expected exit 1, got ${code}`);
    if (cap.stderr.join("\n").includes("error") !== true) {
      throw new Error(`stderr missing error report: ${cap.stderr.join("\n")}`);
    }
  } finally {
    await Deno.remove(tmp, { recursive: true });
  }
});

Deno.test("build writes resolved-config.json and manifest.json", async (t) => {
  const tmp = await Deno.makeTempDir();
  try {
    await scaffoldProject(tmp, FIXTURE_OPENAPI);
    await t.step("build exits 0 and shells the bundle", async () => {
      const cap = capturingCtx(tmp);
      const code = await run(["build", "."], cap.ctx);
      if (code !== 0) throw new Error(`build exited ${code}: ${cap.stderr.join("\n")}`);
      const stdout = cap.stdout.join("\n");
      const builtLine = stdout.split("\n").find((line) => line.startsWith("built "));
      if (builtLine === undefined) {
        throw new Error(`stdout missing built line: ${stdout}`);
      }
      const distDir = builtLine.slice("built ".length).trim();
      await Deno.stat(`${distDir}/index.html`);
    });
    await t.step("resolved-config.json exists and parses", async () => {
      const raw = await Deno.readTextFile(`${tmp}/.berrybench/resolved-config.json`);
      const resolved = JSON.parse(raw) as { workspaces?: Record<string, { enabled?: boolean }> };
      if (resolved.workspaces?.design?.enabled !== true) {
        throw new Error(`design not enabled: ${raw}`);
      }
    });
    await t.step("manifest.json has version and workspaces", async () => {
      const raw = await Deno.readTextFile(`${tmp}/.berrybench/manifest.json`);
      const manifest = JSON.parse(raw) as {
        version?: string;
        generatedAt?: string;
        workspaces?: Record<string, unknown>;
      };
      if (manifest.version !== VERSION) {
        throw new Error(`manifest version ${String(manifest.version)} != ${VERSION}`);
      }
      if (typeof manifest.workspaces !== "object" || manifest.workspaces === null) {
        throw new Error(`manifest workspaces missing: ${raw}`);
      }
      if ("design" in manifest.workspaces !== true || "api" in manifest.workspaces !== true) {
        throw new Error(`manifest workspaces: ${raw}`);
      }
      if (typeof manifest.generatedAt !== "string") {
        throw new Error(`manifest generatedAt missing: ${raw}`);
      }
    });
    await t.step("preview build emitted the iframe app", async () => {
      // The canvas bundle (all three runtimes) lands at <dist>/preview.
      await Deno.stat(`${tmp}/dist/preview/index.html`);
    });
  } finally {
    await Deno.remove(tmp, { recursive: true });
  }
});

Deno.test("config enable/disable toggles a workspace in the config file", async (t) => {
  const tmp = await Deno.makeTempDir();
  try {
    await t.step("enable db prints db: on and persists it", async () => {
      const cap = capturingCtx(tmp);
      const code = await run(["config", "enable", "db", "."], cap.ctx);
      if (code !== 0) throw new Error(`enable exited ${code}: ${cap.stderr.join("\n")}`);
      if (cap.stdout.join("\n").includes("db: on") !== true) {
        throw new Error(`enable stdout: ${cap.stdout.join("\n")}`);
      }
      const file = await readFileConfig(tmp) as {
        workspaces?: Record<string, { enabled?: boolean }>;
      };
      if (file?.workspaces?.db?.enabled !== true) {
        throw new Error(`db not enabled after enable: ${JSON.stringify(file)}`);
      }
    });
    await t.step("disable db flips it back", async () => {
      const cap = capturingCtx(tmp);
      const code = await run(["config", "disable", "db", "."], cap.ctx);
      if (code !== 0) throw new Error(`disable exited ${code}: ${cap.stderr.join("\n")}`);
      const file = await readFileConfig(tmp) as {
        workspaces?: Record<string, { enabled?: boolean }>;
      };
      if (file?.workspaces?.db?.enabled !== false) {
        throw new Error(`db still enabled after disable: ${JSON.stringify(file)}`);
      }
    });
    await t.step("unknown id exits 1 with a message", async () => {
      const cap = capturingCtx(tmp);
      const code = await run(["config", "enable", "nope", "."], cap.ctx);
      if (code !== 1) throw new Error(`expected exit 1, got ${code}`);
      if (cap.stderr.join("\n").includes("unknown workspace: nope") !== true) {
        throw new Error(`stderr missing unknown-workspace message: ${cap.stderr.join("\n")}`);
      }
    });
  } finally {
    await Deno.remove(tmp, { recursive: true });
  }
});

Deno.test("snapshot with an absolute dir writes there, not to cwd", async (t) => {
  const target = await Deno.makeTempDir();
  const cwd = await Deno.makeTempDir();
  try {
    await scaffoldProject(target, FIXTURE_OPENAPI);
    await t.step("snapshots land at the dir argument", async () => {
      const cap = capturingCtx(cwd);
      const code = await run(["snapshot", target], cap.ctx);
      if (code !== 0) throw new Error(`snapshot exited ${code}: ${cap.stderr.join("\n")}`);
      await Deno.stat(`${target}/.berrybench/snapshots/design.json`);
      await Deno.stat(`${target}/.berrybench/snapshots/api.json`);
    });
    await t.step("cwd stays untouched", async () => {
      try {
        await Deno.stat(`${cwd}/.berrybench`);
        throw new Error("snapshots unexpectedly written to cwd");
      } catch (error) {
        if ((error as Error).message.includes("unexpectedly written")) throw error;
      }
    });
  } finally {
    await Deno.remove(target, { recursive: true });
    await Deno.remove(cwd, { recursive: true });
  }
});

Deno.test("parseProjectEnvFile reads .env with the dotenv grammar", async () => {
  const tmp = await Deno.makeTempDir();
  try {
    const dsn = "postgresql://u:p@localhost:5433/db?sslmode=disable";
    await Deno.writeTextFile(
      `${tmp}/.env`,
      [
        "# comment",
        `BERRYBENCH_DATABASE_URL=${dsn}`,
        "export QUOTED='single quoted'",
        'DOUBLE="double quoted"',
        "EMPTY=",
      ].join("\n"),
    );
    const parsed = parseProjectEnvFile(tmp);
    if (parsed.BERRYBENCH_DATABASE_URL !== dsn) {
      throw new Error(`dsn parsed wrong: ${JSON.stringify(parsed)}`);
    }
    if (parsed.QUOTED !== "single quoted" || parsed.DOUBLE !== "double quoted") {
      throw new Error(`quotes not stripped: ${JSON.stringify(parsed)}`);
    }
    if (parsed.EMPTY !== "") {
      throw new Error(`empty value not parsed: ${JSON.stringify(parsed)}`);
    }
  } finally {
    await Deno.remove(tmp, { recursive: true });
  }
});

Deno.test("parseProjectEnvFile yields {} without a .env", async () => {
  const tmp = await Deno.makeTempDir();
  try {
    const parsed = parseProjectEnvFile(tmp);
    if (Object.keys(parsed).length !== 0) {
      throw new Error(`expected {} got ${JSON.stringify(parsed)}`);
    }
  } finally {
    await Deno.remove(tmp, { recursive: true });
  }
});

Deno.test("projectDirFromArgs mirrors each command's dir-arg parsing", () => {
  const cases: Array<[string[], string, string]> = [
    [["dev"], "/work", "/work"],
    [["dev", "site"], "/work", "/work/site"],
    [["dev", "/abs", "--watch"], "/work", "/abs"],
    [["snapshot", "--strict", "."], "/work", "/work"],
    [["build", "site"], "/work", "/work/site"],
    [["init", "/abs"], "/work", "/abs"],
    [["config", "enable", "db", "site"], "/work", "/work/site"],
    [["config", "disable", "db", "/abs"], "/work", "/abs"],
    [["config", "--print"], "/work", "/work"],
  ];
  for (const [args, cwd, expected] of cases) {
    const got = projectDirFromArgs(args, cwd);
    if (got !== expected) {
      throw new Error(`${JSON.stringify(args)} -> ${got}, expected ${expected}`);
    }
  }
});

/** Repo root: main_test.ts lives at packages/cli/. */
const REPO_ROOT = join(import.meta.dirname!, "../..");

Deno.test("the CLI entrypoint loads .env from the project root", async () => {
  const tmp = await Deno.makeTempDir();
  // Isolate the child from any BERRYBENCH_* vars exported in this environment.
  const env: Record<string, string> = {};
  for (const [key, value] of Object.entries(Deno.env.toObject())) {
    if (!key.startsWith("BERRYBENCH_")) env[key] = value;
  }
  try {
    await Deno.writeTextFile(
      `${tmp}/berrybench.config.ts`,
      "export default { workspaces: { db: { enabled: true } } };\n",
    );
    const snapshotOnce = async (): Promise<string> => {
      const cmd = new Deno.Command(Deno.execPath(), {
        args: ["run", "-A", "packages/cli/main.ts", "snapshot", tmp],
        cwd: REPO_ROOT,
        env,
        stdout: "piped",
        stderr: "piped",
      });
      const { code, stdout, stderr } = await cmd.output();
      if (code !== 0) {
        throw new Error(`snapshot exited ${code}: ${new TextDecoder().decode(stderr)}`);
      }
      return new TextDecoder().decode(stdout);
    };

    const without = await snapshotOnce();
    if (/db: on \(\w+\) · error: no database connection configured/.test(without) !== true) {
      throw new Error(`expected no-connection error without .env: ${without}`);
    }

    await Deno.writeTextFile(`${tmp}/.env`, "BERRYBENCH_DATABASE_URL=not-a-url\n");
    const withDotEnv = await snapshotOnce();
    if (/db: on \(\w+\) · error: database connection failed/.test(withDotEnv) !== true) {
      throw new Error(`expected connection-failure error with .env: ${withDotEnv}`);
    }
  } finally {
    await Deno.remove(tmp, { recursive: true });
  }
});
